### PR TITLE
Adding feature: Partial range download

### PR DESCRIPTION
**Pull request by namdien177**
Reason and basic implementation are described in #27.

Since I am not familiar with the `request` package (tested with `node-fetch` OK ) so there might be some mistake.

<s>Also, because there is no guide to perform testing and stuff and I have tried to test it, it seems like the `uploadSimple` API has some issue on the test case with `parentPath`.
Can you check that?</s>

testing with E2E seems to be fine.

> image

### CODE REVIEW

**Comment by namdien177** [comment]
I found some mistake in the `README.md`, gonna fix it later.

**Review by dkatavic — APPROVED** [review]
This is an amazing contribution @namdien177 , Thank you 💯 

Thanks for fixing the documentation. Good job on figuring out how to run e2e tests, unfortunately, OneDrive doesn't offer sandbox env that I could use for running automated e2e tests so it is not easy to figure out how to run them. They are passing for me. Let me know if you have any suggestions on how to improve the project

Great job again

**Comment by dkatavic** [comment]
@namdien177 I have added you as a collaborator on a project, when you resolve the conflict you can squash and merge 👍

**Comment by namdien177** [comment]
thanks.
By the way, I was wondering what was this PR for: [Feature/add query param](https://github.com/dkatavic/onedrive-api/commit/3a8a064d701689256756db91b36b69ace7cd9b23).
File concern: [listChildren.js](lib/items/listChildren.js)

As far as I understand, the query here doesn't do anything and the PR was just for adding optional params and change the README content. Am I wrong here?

If I was right then I would recommend a new PR to add the query string option to all APIs (and exclude the README changes or add a WIP tag to the option from this PR to prevent confusion).

**Comment by dkatavic** [comment]
You are correct, query was correctly added as a parameter in this [commit](https://github.com/dkatavic/onedrive-api/pull/24/commits/adcff23ecccb7a97dfc9687eec3f0063efe05976) , but  because of a bad merge it was removed [here](https://github.com/dkatavic/onedrive-api/pull/24/commits/6ece2030187f516aeaf50bd865c5389a980b0af8)

I will submit a fix for this. I'm up for adding OData query to all APIs

**Comment by namdien177** [comment]
> You are correct, query was correctly added as a parameter in this [commit](https://github.com/dkatavic/onedrive-api/pull/24/commits/adcff23ecccb7a97dfc9687eec3f0063efe05976) , but because of a bad merge it was removed [here](https://github.com/dkatavic/onedrive-api/pull/24/commits/6ece2030187f516aeaf50bd865c5389a980b0af8)
> 
> I will submit a fix for this. I'm up for adding OData query to all APIs

Glad to hear this feature will be coming soon.
And by the way, can you re-approve the changes? The CI build was `waiting for the status to be reported` and I don't know how to change/update/fix this to finish CI so I'm assuming getting a new approval will resolve this. Can you check that for me?

**Review by dkatavic — APPROVED** [review]

**Comment by dkatavic** [comment]
@namdien177 Fixed

**Pull request merged**
